- hosts: localhost
  connection: local
  gather_facts: False
  
  vars_files:
  - vars/dev-environment.yml
  - vars/aws-creds.yml

  tasks:

    - name: Provision a set of instances
      ec2:
        region: "{{ ec2_region }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        keypair: "{{ instances_keypair }}"
        group: default
        instance_type: t2.micro
        image: "{{ image_id }}"
        wait: true
        exact_count: 2
        count_tag:
           Name: Demo
        instance_tags:
           Name: Demo
      register: ec2